### ISSUE TITLE
Roadmap to 0.7.0

### ISSUE THREAD

**Issue by tisonkun** [fast/fastrace#8]
- [x] #12
- [x] https://github.com/fastracelabs/fastrace/issues/15
- [x] https://github.com/fastracelabs/fastrace/issues/10
- [x] https://github.com/fastracelabs/fastrace/issues/17
- [x] https://github.com/fast/fastrace/issues/24

**Comment by Xuanwo** [comment]
Hi, thanks a lot for start this issue first!

I personally feel that reexporting `opentelemetry` is not a good idea. Ideally, users should not access `opentelemetry` through `fastrace` as they might have other integrations with it. I propose releasing `fastrace-opentelemetry` separately, and its version should be updated every time there's a new release of either `fastrace` or `opentelemetry`.

**Comment by tisonkun** [comment]
@andylokandy I noticed that `opentelemetry-otlp` is common used for implement fastrace exporter impl. But if we re-export opentelemetry crates, only `opentelemetry` and `opentelemetry_sdk` re-exported, no `opentelemetry-otlp`.

**Comment by andylokandy** [comment]
opentelemetry-otlp seems to bound with opentelemetry_sdk, so it's not viable to only reexport opentelemetry_sdk

**Comment by andylokandy** [comment]
0.7.0 released https://crates.io/crates/fastrace
